global using CodeDesignPlus.Net.EventStore.Abstractions;
global using CodeDesignPlus.Net.EventStore.Abstractions.Options;
global using CodeDesignPlus.Net.EventStore.Exceptions;
global using CodeDesignPlus.Net.EventStore.Services;
global using CodeDesignPlus.Net.EventStore.Test.Helpers;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Xunit;
