global using System;
global using System.Linq;
global using System.Runtime.Serialization;
global using System.Threading.Tasks;
global using CodeDesignPlus.Net.Core.Abstractions;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Serialization;
