services:
  mongo1:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "${PORT_CUSTOM}"]
    ports:
      - ${PORT_CUSTOM}:${PORT_CUSTOM}
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:${PORT_CUSTOM}'}]}) }" | mongosh --port ${PORT_CUSTOM} --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    networks:
      - backend
networks:
  backend:
