global using CodeDesignPlus.Net.File.Storage.Abstractions;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using System;
global using System.Threading.Tasks;
global using CodeDesignPlus.Net.File.Storage.Abstractions.Factories;
global using CodeDesignPlus.Net.File.Storage.Abstractions.Options;
global using CodeDesignPlus.Net.File.Storage.Abstractions.Providers;
global using CodeDesignPlus.Net.File.Storage.Exceptions;
global using CodeDesignPlus.Net.File.Storage.Factories;
global using CodeDesignPlus.Net.File.Storage.Providers;
global using CodeDesignPlus.Net.File.Storage.Services;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Azure.Identity;
global using Azure.Storage.Blobs;
global using CodeDesignPlus.Net.Security.Abstractions;
global using Azure.Storage.Files.Shares;
global using Azure.Storage.Blobs.Models;
global using Microsoft.Extensions.Hosting;
global using Semver;
global using System.Text;
global using M = CodeDesignPlus.Net.File.Storage.Abstractions.Models;

