receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
      - job_name: otel-collector
        scrape_interval: 5s
        static_configs:
        - targets: [localhost:8888]
      - job_name: 'ms-archetype'
        scrape_interval: 5s
        static_configs:
        - targets: ['host.docker.internal:5175']

exporters:
  loki:
    endpoint: "http://host.docker.internal:3100/loki/api/v1/push"
  otlp:
    endpoint: host.docker.internal:4320
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    
    logs:
      receivers: [otlp]
      exporters: [loki]

    metrics:
      receivers: [otlp, prometheus]
      exporters: [prometheus]

  telemetry:
    logs:
      level: DEBUG
      initial_fields:
        service: my-instance
    metrics:
      level: detailed
      address: 0.0.0.0:8888