global:

scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector-contrib:8889"]
      - targets: ["otel-collector-contrib:8888"]
    
  #- job_name: 'ms-archetype-pr'
  #  scrape_interval: 5s # Poll every 5 seconds for a more responsive demo.
  #  static_configs:
  #  - targets: ["host.docker.internal:5175"] 