services:
  otel-collector:
    image: otel/opentelemetry-collector
    ports:
      - "0:4317"
      - "0:4318"
    volumes:
      - ./collector-config.yml:/etc/otelcol/config.yaml
    restart: always
