services:
  servicebus:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - "./Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "0:5672"
      - "0:5300"
    environment:
      ACCEPT_EULA: "Y"
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "Temporal1.Temporal1"
    depends_on:
      - sqledge
  sqledge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Temporal1.Temporal1"
